version: '3'
services:
  mycassandra:
    image: cassandra:3.11.2
    container_name: my-cassandra-node
    ports:
      - "9042:9042"
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "app_updates:1:3"